Update AVI to AVAM to reflect new service name
Azure-Samples/media-services-video-indexer pull request #11
Opened 2021-06-07 12:06 UTC by shanepeckham

2021-06-07 13:38 UTC, ika-microsoft requested changes
There are many wrong search and replaces.

2021-06-07 13:38 UTC, ika-microsoft commented on VideoSearchWithAutoMLVision/README.md
> +After Terraform reports that the apply is complete, if you nAVAMgate to your resource group, hAVAMng used the default
Typo

2021-06-07 13:38 UTC, ika-microsoft commented on VideoSearchWithAutoMLVision/README.md
> +If we nAVAMgate to this resource's overview, and scroll down, there is a window entitled "Azure Video Analyzer for Media". Click the link
Here same

2021-06-07 13:38 UTC, ika-microsoft commented on VideoSearchWithAutoMLVision/README.md
> +Sign in using the same AAD account, and go to "Profile" in the nAVAMgation bar.
Same here. Please fix all over the place

2022-04-27 17:54 UTC, tshaiman approved these changes
LGTM

2022-04-27 17:54 UTC, merged